// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides automatic type augmentation for decorated classes

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

import type { ProtoFlat } from 'mnemonica';

export {};

declare global {

	type StandardType_StandardSubtype = ProtoFlat<StandardType, {
		subtypeData: string;
		StandardSubtype: undefined;
	}>;

	type BaseEntity_UserEntity = ProtoFlat<BaseEntity, {
		username: string;
		email: string;
		isActive: boolean;
		AdminEntity: new () => BaseEntity_UserEntity_AdminEntity;
		UserEntity: undefined;
		ProductEntity: undefined;
	}>;

	type BaseEntity_UserEntity_AdminEntity = ProtoFlat<BaseEntity_UserEntity, {
		role: string;
		permissions: Array<string>;
		AdminEntity: undefined;
	}>;

	type BaseEntity_ProductEntity = ProtoFlat<BaseEntity, {
		sku: string;
		name: string;
		price: number;
		ProductEntity: undefined;
		UserEntity: undefined;
	}>;

	type GlobalUserType_GlobalAdminType = ProtoFlat<GlobalUserType, {
		role: string;
		permissions: Array<unknown>;
		GlobalSuperAdminType: new () => GlobalUserType_GlobalAdminType_GlobalSuperAdminType;
		GlobalAdminType: undefined;
	}>;

	type GlobalUserType_GlobalAdminType_GlobalSuperAdminType = ProtoFlat<GlobalUserType_GlobalAdminType, {
		isSystemAdmin: boolean;
		accessLevel: number;
		GlobalSuperAdminType: undefined;
	}>;

	type GlobalOrder_GlobalAugmentedOrder = ProtoFlat<GlobalOrder, {
		addition: string;
		GlobalAugmentedOrderNext: new () => GlobalOrder_GlobalAugmentedOrder_GlobalAugmentedOrderNext;
		GlobalAugmentedOrder: undefined;
	}>;

	type GlobalOrder_GlobalAugmentedOrder_GlobalAugmentedOrderNext = ProtoFlat<GlobalOrder_GlobalAugmentedOrder, {
		next: number;
		GlobalAugmentedOrderNext: undefined;
	}>;

	type UserType_AdminType = ProtoFlat<UserType, {
		role: string;
		permissions: Array<unknown>;
		SuperAdminType: new () => UserType_AdminType_SuperAdminType;
		AdminType: undefined;
	}>;

	type UserType_AdminType_SuperAdminType = ProtoFlat<UserType_AdminType, {
		isSystemAdmin: boolean;
		accessLevel: number;
		SuperAdminType: undefined;
	}>;

	type Order_AugmentedOrder = ProtoFlat<Order, {
		addition: string;
		AugmentedOrderNext: new () => Order_AugmentedOrder_AugmentedOrderNext;
		AugmentedOrder: undefined;
	}>;

	type Order_AugmentedOrder_AugmentedOrderNext = ProtoFlat<Order_AugmentedOrder, {
		next: number;
		AugmentedOrderNext: undefined;
	}>;

	type RefUserType_RefAdminType = ProtoFlat<RefUserType, {
		role: string;
		permissions: Array<unknown>;
		RefSuperAdminType: new () => RefUserType_RefAdminType_RefSuperAdminType;
		RefAdminType: undefined;
	}>;

	type RefUserType_RefAdminType_RefSuperAdminType = ProtoFlat<RefUserType_RefAdminType, {
		isSystemAdmin: boolean;
		accessLevel: number;
		RefSuperAdminType: undefined;
	}>;

	type RefOrder_RefAugmentedOrder = ProtoFlat<RefOrder, {
		addition: string;
		RefAugmentedOrderNext: new () => RefOrder_RefAugmentedOrder_RefAugmentedOrderNext;
		RefAugmentedOrder: undefined;
	}>;

	type RefOrder_RefAugmentedOrder_RefAugmentedOrderNext = ProtoFlat<RefOrder_RefAugmentedOrder, {
		next: number;
		RefAugmentedOrderNext: undefined;
	}>;

	type ProductType_DigitalProductType = ProtoFlat<ProductType, {
		downloadUrl: string;
		fileSize: number;
		format: string;
		DigitalProductType: undefined;
		PhysicalProductType: undefined;
	}>;

	type ProductType_PhysicalProductType = ProtoFlat<ProductType, {
		weight: number;
		dimensions: object;
		inStock: boolean;
		PhysicalProductType: undefined;
		DigitalProductType: undefined;
	}>;

	type CustomerType_PremiumCustomerType = ProtoFlat<CustomerType, {
		loyaltyPoints: number;
		membershipLevel: string;
		PremiumCustomerType: undefined;
	}>;

	type ServiceType_WebServiceType = ProtoFlat<ServiceType, {
		endpoint: string;
		method: string;
		WebServiceType: undefined;
		DatabaseServiceType: undefined;
	}>;

	type ServiceType_DatabaseServiceType = ProtoFlat<ServiceType, {
		connectionString: string;
		poolSize: number;
		DatabaseServiceType: undefined;
		WebServiceType: undefined;
	}>;

	type ConfigType_ProductionConfigType = ProtoFlat<ConfigType, {
		env: string;
		ssl: boolean;
		caching: boolean;
		ProductionConfigType: undefined;
	}>;

	type StrictEntity_StrictChild = ProtoFlat<StrictEntity, {
		childValue: string;
		StrictChild: undefined;
	}>;

	type BaseWithPrototype_DerivedFromBase = ProtoFlat<BaseWithPrototype, {
		derivedField: number;
		extra: string;
		DerivedFromBase: undefined;
	}>;

	// Class interfaces for declaration merging
	// These merge with @decorate() classes to provide proper typing

	interface StandardType {
		data: string;
		StandardSubtype: new () => StandardType_StandardSubtype;
	}

	interface StandardSubtype extends StandardType {
		subtypeData: string;
	}

	interface StrictType {
		data: string;
	}

	interface BaseEntity {
		id: string;
		createdAt: Date;
		updatedAt: Date;
		UserEntity: new () => BaseEntity_UserEntity;
		ProductEntity: new () => BaseEntity_ProductEntity;
	}

	interface UserEntity extends BaseEntity {
		username: string;
		email: string;
		isActive: boolean;
	}

	interface AdminEntity extends UserEntity {
		role: string;
		permissions: Array<string>;
	}

	interface ProductEntity extends BaseEntity {
		sku: string;
		name: string;
		price: number;
	}

	interface ConfigurableEntity {
		config: Record<string, unknown>;
	}

	interface ExcludeExampleUser {
		name: string;
		email: string;
	}

	interface ExcludeExampleOrder {
		orderId: string;
		total: number;
	}

	interface GlobalUserType {
		name: string;
		email: string;
		createdAt: Date;
		GlobalAdminType: new () => GlobalUserType_GlobalAdminType;
	}

	interface GlobalAdminType extends GlobalUserType {
		role: string;
		permissions: Array<unknown>;
	}

	interface GlobalSuperAdminType extends GlobalAdminType {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	interface GlobalOrder {
		orderId: string;
		total: number;
		GlobalAugmentedOrder: new () => GlobalOrder_GlobalAugmentedOrder;
	}

	interface GlobalAugmentedOrder extends GlobalOrder {
		addition: string;
	}

	interface GlobalAugmentedOrderNext extends GlobalAugmentedOrder {
		next: number;
	}

	interface UserType {
		name: string;
		email: string;
		createdAt: Date;
		AdminType: new () => UserType_AdminType;
	}

	interface AdminType extends UserType {
		role: string;
		permissions: Array<unknown>;
	}

	interface SuperAdminType extends AdminType {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	interface Order {
		orderId: string;
		total: number;
		AugmentedOrder: new () => Order_AugmentedOrder;
	}

	interface AugmentedOrder extends Order {
		addition: string;
	}

	interface AugmentedOrderNext extends AugmentedOrder {
		next: number;
	}

	interface RefUserType {
		name: string;
		email: string;
		createdAt: Date;
		RefAdminType: new () => RefUserType_RefAdminType;
	}

	interface RefAdminType extends RefUserType {
		role: string;
		permissions: Array<unknown>;
	}

	interface RefSuperAdminType extends RefAdminType {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	interface RefOrder {
		orderId: string;
		total: number;
		RefAugmentedOrder: new () => RefOrder_RefAugmentedOrder;
	}

	interface RefAugmentedOrder extends RefOrder {
		addition: string;
	}

	interface RefAugmentedOrderNext extends RefAugmentedOrder {
		next: number;
	}

	interface SomeNewType {
		name: string;
		email: string;
		filed: number;
	}

	interface ProductType {
		id: string;
		name: string;
		price: number;
		DigitalProductType: new () => ProductType_DigitalProductType;
		PhysicalProductType: new () => ProductType_PhysicalProductType;
	}

	interface DigitalProductType extends ProductType {
		downloadUrl: string;
		fileSize: number;
		format: string;
	}

	interface PhysicalProductType extends ProductType {
		weight: number;
		dimensions: object;
		inStock: boolean;
	}

	interface CustomerType {
		id: string;
		name: string;
		email: string;
		PremiumCustomerType: new () => CustomerType_PremiumCustomerType;
	}

	interface PremiumCustomerType extends CustomerType {
		loyaltyPoints: number;
		membershipLevel: string;
	}

	interface Invoice {
		invoiceId: string;
		amount: number;
		issuedAt: Date;
	}

	interface Payment {
		paymentId: string;
		method: string;
		status: 'pending' | 'completed' | 'failed';
	}

	interface ServiceType {
		id: string;
		name: string;
		description: string;
		WebServiceType: new () => ServiceType_WebServiceType;
		DatabaseServiceType: new () => ServiceType_DatabaseServiceType;
	}

	interface WebServiceType extends ServiceType {
		endpoint: string;
		method: string;
	}

	interface DatabaseServiceType extends ServiceType {
		connectionString: string;
		poolSize: number;
	}

	interface ConfigType {
		env: string;
		debug: boolean;
		ProductionConfigType: new () => ConfigType_ProductionConfigType;
	}

	interface ProductionConfigType extends ConfigType {
		env: string;
		ssl: boolean;
		caching: boolean;
	}

	interface Logger {
		level: 'debug' | 'info' | 'warn' | 'error';
		prefix: string;
	}

	interface Cache {
		ttl: number;
		maxSize: number;
	}

	interface StrictEntity {
		value: string;
		count: number;
		StrictChild: new () => StrictEntity_StrictChild;
	}

	interface StrictChild extends StrictEntity {
		childValue: string;
	}

	interface BaseWithPrototype {
		baseField: number;
		name: string;
		DerivedFromBase: new () => BaseWithPrototype_DerivedFromBase;
	}

	interface DerivedFromBase extends BaseWithPrototype {
		derivedField: number;
		extra: string;
	}

	interface MyFnType {
	}

	interface AssignType {
	}

	interface MultiDecorated {
		strictField: string;
	}

}