// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides automatic type augmentation for decorated classes

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

export {};

declare global {

	// Helper type for nested type constructors
	type TypeConstructor<T> = {
		new (...args: unknown[]): T;
		(...args: unknown[]): T;
	};

	type StandardTypeInstance = {
		data: string;
		StandardSubtype: TypeConstructor<StandardSubtypeInstance>;
	}

	type StandardSubtypeInstance = StandardTypeInstance & {
		subtypeData: string;
	}

	type HiddenMethodsTypeInstance = {
		data: string;
		HiddenSubtype: TypeConstructor<HiddenSubtypeInstance>;
	}

	type HiddenSubtypeInstance = HiddenMethodsTypeInstance & {
		subtypeData: string;
	}

	type HiddenTypeShorthandInstance = {
		data: string;
	}

	type StrictTypeInstance = {
		data: string;
	}

	type BaseEntityInstance = {
		id: string;
		createdAt: Date;
		updatedAt: Date;
		UserEntity: TypeConstructor<UserEntityInstance>;
		ProductEntity: TypeConstructor<ProductEntityInstance>;
	}

	type UserEntityInstance = BaseEntityInstance & {
		username: string;
		email: string;
		isActive: boolean;
		AdminEntity: TypeConstructor<AdminEntityInstance>;
	}

	type AdminEntityInstance = UserEntityInstance & {
		role: string;
		permissions: Array<string>;
	}

	type ProductEntityInstance = BaseEntityInstance & {
		sku: string;
		name: string;
		price: number;
	}

	type ConfigurableEntityInstance = {
		config: object;
	}

	type ExcludeExampleUserInstance = {
		name: string;
		email: string;
	}

	type ExcludeExampleOrderInstance = {
		orderId: string;
		total: number;
	}

	type GlobalUserTypeInstance = {
		name: string;
		email: string;
		createdAt: Date;
		GlobalAdminType: TypeConstructor<GlobalAdminTypeInstance>;
	}

	type GlobalAdminTypeInstance = GlobalUserTypeInstance & {
		role: string;
		permissions: Array<unknown>;
		GlobalSuperAdminType: TypeConstructor<GlobalSuperAdminTypeInstance>;
	}

	type GlobalSuperAdminTypeInstance = GlobalAdminTypeInstance & {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	type GlobalOrderInstance = {
		orderId: string;
		total: number;
		GlobalAugmentedOrder: TypeConstructor<GlobalAugmentedOrderInstance>;
	}

	type GlobalAugmentedOrderInstance = GlobalOrderInstance & {
		addition: string;
		GlobalAugmentedOrderNext: TypeConstructor<GlobalAugmentedOrderNextInstance>;
	}

	type GlobalAugmentedOrderNextInstance = GlobalAugmentedOrderInstance & {
		next: number;
	}

	type UserTypeInstance = {
		name: string;
		email: string;
		createdAt: Date;
		AdminType: TypeConstructor<AdminTypeInstance>;
	}

	type AdminTypeInstance = UserTypeInstance & {
		role: string;
		permissions: Array<unknown>;
		SuperAdminType: TypeConstructor<SuperAdminTypeInstance>;
	}

	type SuperAdminTypeInstance = AdminTypeInstance & {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	type OrderInstance = {
		orderId: string;
		total: number;
		AugmentedOrder: TypeConstructor<AugmentedOrderInstance>;
	}

	type AugmentedOrderInstance = OrderInstance & {
		addition: string;
		AugmentedOrderNext: TypeConstructor<AugmentedOrderNextInstance>;
	}

	type AugmentedOrderNextInstance = AugmentedOrderInstance & {
		next: number;
	}

	type RefUserTypeInstance = {
		name: string;
		email: string;
		createdAt: Date;
		RefAdminType: TypeConstructor<RefAdminTypeInstance>;
	}

	type RefAdminTypeInstance = RefUserTypeInstance & {
		role: string;
		permissions: Array<unknown>;
		RefSuperAdminType: TypeConstructor<RefSuperAdminTypeInstance>;
	}

	type RefSuperAdminTypeInstance = RefAdminTypeInstance & {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	type RefOrderInstance = {
		orderId: string;
		total: number;
		RefAugmentedOrder: TypeConstructor<RefAugmentedOrderInstance>;
	}

	type RefAugmentedOrderInstance = RefOrderInstance & {
		addition: string;
		RefAugmentedOrderNext: TypeConstructor<RefAugmentedOrderNextInstance>;
	}

	type RefAugmentedOrderNextInstance = RefAugmentedOrderInstance & {
		next: number;
	}

	type ProductTypeInstance = {
		id: string;
		name: string;
		price: number;
		DigitalProductType: TypeConstructor<DigitalProductTypeInstance>;
		PhysicalProductType: TypeConstructor<PhysicalProductTypeInstance>;
	}

	type DigitalProductTypeInstance = ProductTypeInstance & {
		downloadUrl: string;
		fileSize: number;
		format: string;
	}

	type PhysicalProductTypeInstance = ProductTypeInstance & {
		weight: number;
		dimensions: object;
		inStock: boolean;
	}

	type CustomerTypeInstance = {
		id: string;
		name: string;
		email: string;
		PremiumCustomerType: TypeConstructor<PremiumCustomerTypeInstance>;
	}

	type PremiumCustomerTypeInstance = CustomerTypeInstance & {
		loyaltyPoints: number;
		membershipLevel: string;
	}

	type InvoiceInstance = {
		invoiceId: string;
		amount: number;
		issuedAt: Date;
	}

	type PaymentInstance = {
		paymentId: string;
		method: string;
		status: string;
	}

	type ServiceTypeInstance = {
		id: string;
		name: string;
		description: string;
		WebServiceType: TypeConstructor<WebServiceTypeInstance>;
		DatabaseServiceType: TypeConstructor<DatabaseServiceTypeInstance>;
	}

	type WebServiceTypeInstance = ServiceTypeInstance & {
		endpoint: string;
		method: string;
	}

	type DatabaseServiceTypeInstance = ServiceTypeInstance & {
		connectionString: string;
		poolSize: number;
	}

	type ConfigTypeInstance = {
		env: string;
		debug: boolean;
		ProductionConfigType: TypeConstructor<ProductionConfigTypeInstance>;
	}

	type ProductionConfigTypeInstance = ConfigTypeInstance & {
		env: string;
		ssl: boolean;
		caching: boolean;
	}

	type LoggerInstance = {
		level: string;
		prefix: string;
	}

	type CacheInstance = {
		ttl: number;
		maxSize: number;
	}

	type StrictEntityInstance = {
		value: string;
		count: number;
		StrictChild: TypeConstructor<StrictChildInstance>;
	}

	type StrictChildInstance = StrictEntityInstance & {
		childValue: string;
	}

	type BaseWithPrototypeInstance = {
		baseField: number;
		name: string;
		DerivedFromBase: TypeConstructor<DerivedFromBaseInstance>;
	}

	type DerivedFromBaseInstance = BaseWithPrototypeInstance & {
		derivedField: number;
		extra: string;
	}

	type MyFnTypeInstance = {
	}

	type AssignTypeInstance = {
	}

	type MultiDecoratedInstance = {
		strictField: string;
	}

	// Class interfaces for declaration merging
	// These merge with @decorate() classes to provide proper typing

	interface StandardType {
		data: string;
		StandardSubtype: TypeConstructor<StandardSubtypeInstance>;
	}

	interface StandardSubtype extends StandardType {
		subtypeData: string;
	}

	interface HiddenMethodsType {
		data: string;
		HiddenSubtype: TypeConstructor<HiddenSubtypeInstance>;
	}

	interface HiddenSubtype extends HiddenMethodsType {
		subtypeData: string;
	}

	interface HiddenTypeShorthand {
		data: string;
	}

	interface StrictType {
		data: string;
	}

	interface BaseEntity {
		id: string;
		createdAt: Date;
		updatedAt: Date;
		UserEntity: TypeConstructor<UserEntityInstance>;
		ProductEntity: TypeConstructor<ProductEntityInstance>;
	}

	interface UserEntity extends BaseEntity {
		username: string;
		email: string;
		isActive: boolean;
		AdminEntity: TypeConstructor<AdminEntityInstance>;
	}

	interface AdminEntity extends UserEntity {
		role: string;
		permissions: Array<string>;
	}

	interface ProductEntity extends BaseEntity {
		sku: string;
		name: string;
		price: number;
	}

	interface ConfigurableEntity {
		config: object;
	}

	interface ExcludeExampleUser {
		name: string;
		email: string;
	}

	interface ExcludeExampleOrder {
		orderId: string;
		total: number;
	}

	interface GlobalUserType {
		name: string;
		email: string;
		createdAt: Date;
		GlobalAdminType: TypeConstructor<GlobalAdminTypeInstance>;
	}

	interface GlobalAdminType extends GlobalUserType {
		role: string;
		permissions: Array<unknown>;
		GlobalSuperAdminType: TypeConstructor<GlobalSuperAdminTypeInstance>;
	}

	interface GlobalSuperAdminType extends GlobalAdminType {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	interface GlobalOrder {
		orderId: string;
		total: number;
		GlobalAugmentedOrder: TypeConstructor<GlobalAugmentedOrderInstance>;
	}

	interface GlobalAugmentedOrder extends GlobalOrder {
		addition: string;
		GlobalAugmentedOrderNext: TypeConstructor<GlobalAugmentedOrderNextInstance>;
	}

	interface GlobalAugmentedOrderNext extends GlobalAugmentedOrder {
		next: number;
	}

	interface UserType {
		name: string;
		email: string;
		createdAt: Date;
		AdminType: TypeConstructor<AdminTypeInstance>;
	}

	interface AdminType extends UserType {
		role: string;
		permissions: Array<unknown>;
		SuperAdminType: TypeConstructor<SuperAdminTypeInstance>;
	}

	interface SuperAdminType extends AdminType {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	interface Order {
		orderId: string;
		total: number;
		AugmentedOrder: TypeConstructor<AugmentedOrderInstance>;
	}

	interface AugmentedOrder extends Order {
		addition: string;
		AugmentedOrderNext: TypeConstructor<AugmentedOrderNextInstance>;
	}

	interface AugmentedOrderNext extends AugmentedOrder {
		next: number;
	}

	interface RefUserType {
		name: string;
		email: string;
		createdAt: Date;
		RefAdminType: TypeConstructor<RefAdminTypeInstance>;
	}

	interface RefAdminType extends RefUserType {
		role: string;
		permissions: Array<unknown>;
		RefSuperAdminType: TypeConstructor<RefSuperAdminTypeInstance>;
	}

	interface RefSuperAdminType extends RefAdminType {
		isSystemAdmin: boolean;
		accessLevel: number;
	}

	interface RefOrder {
		orderId: string;
		total: number;
		RefAugmentedOrder: TypeConstructor<RefAugmentedOrderInstance>;
	}

	interface RefAugmentedOrder extends RefOrder {
		addition: string;
		RefAugmentedOrderNext: TypeConstructor<RefAugmentedOrderNextInstance>;
	}

	interface RefAugmentedOrderNext extends RefAugmentedOrder {
		next: number;
	}

	interface ProductType {
		id: string;
		name: string;
		price: number;
		DigitalProductType: TypeConstructor<DigitalProductTypeInstance>;
		PhysicalProductType: TypeConstructor<PhysicalProductTypeInstance>;
	}

	interface DigitalProductType extends ProductType {
		downloadUrl: string;
		fileSize: number;
		format: string;
	}

	interface PhysicalProductType extends ProductType {
		weight: number;
		dimensions: object;
		inStock: boolean;
	}

	interface CustomerType {
		id: string;
		name: string;
		email: string;
		PremiumCustomerType: TypeConstructor<PremiumCustomerTypeInstance>;
	}

	interface PremiumCustomerType extends CustomerType {
		loyaltyPoints: number;
		membershipLevel: string;
	}

	interface Invoice {
		invoiceId: string;
		amount: number;
		issuedAt: Date;
	}

	interface Payment {
		paymentId: string;
		method: string;
		status: string;
	}

	interface ServiceType {
		id: string;
		name: string;
		description: string;
		WebServiceType: TypeConstructor<WebServiceTypeInstance>;
		DatabaseServiceType: TypeConstructor<DatabaseServiceTypeInstance>;
	}

	interface WebServiceType extends ServiceType {
		endpoint: string;
		method: string;
	}

	interface DatabaseServiceType extends ServiceType {
		connectionString: string;
		poolSize: number;
	}

	interface ConfigType {
		env: string;
		debug: boolean;
		ProductionConfigType: TypeConstructor<ProductionConfigTypeInstance>;
	}

	interface ProductionConfigType extends ConfigType {
		env: string;
		ssl: boolean;
		caching: boolean;
	}

	interface Logger {
		level: string;
		prefix: string;
	}

	interface Cache {
		ttl: number;
		maxSize: number;
	}

	interface StrictEntity {
		value: string;
		count: number;
		StrictChild: TypeConstructor<StrictChildInstance>;
	}

	interface StrictChild extends StrictEntity {
		childValue: string;
	}

	interface BaseWithPrototype {
		baseField: number;
		name: string;
		DerivedFromBase: TypeConstructor<DerivedFromBaseInstance>;
	}

	interface DerivedFromBase extends BaseWithPrototype {
		derivedField: number;
		extra: string;
	}

	interface MyFnType {
	}

	interface AssignType {
	}

	interface MultiDecorated {
		strictField: string;
	}

}