// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides complete TypeScript interfaces for Mnemonica types

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

import type { ProtoFlat } from 'mnemonica';

export type StandardType = {
	data: string;
	StandardSubtype: {
		new (): StandardType_StandardSubtype;
		(): StandardType_StandardSubtype;
	};
};

export type StandardType_StandardSubtype = ProtoFlat<StandardType, {
	subtypeData: string;
	StandardSubtype: undefined;
}>;

export type StrictType = {
	data: string;
};

export type BaseEntity = {
	id: string;
	createdAt: Date;
	updatedAt: Date;
	UserEntity: {
		new (): BaseEntity_UserEntity;
		(): BaseEntity_UserEntity;
	};
	ProductEntity: {
		new (): BaseEntity_ProductEntity;
		(): BaseEntity_ProductEntity;
	};
};

export type BaseEntity_UserEntity = ProtoFlat<BaseEntity, {
	username: string;
	email: string;
	isActive: boolean;
	AdminEntity: {
		new (): BaseEntity_UserEntity_AdminEntity;
		(): BaseEntity_UserEntity_AdminEntity;
	};
	UserEntity: undefined;
	ProductEntity: undefined;
}>;

export type BaseEntity_UserEntity_AdminEntity = ProtoFlat<BaseEntity_UserEntity, {
	role: string;
	permissions: Array<string>;
	AdminEntity: undefined;
}>;

export type BaseEntity_ProductEntity = ProtoFlat<BaseEntity, {
	sku: string;
	name: string;
	price: number;
	ProductEntity: undefined;
	UserEntity: undefined;
}>;

export type ConfigurableEntity = {
	config: Record<string, unknown>;
};

export type ExcludeExampleUser = {
	name: string;
	email: string;
};

export type ExcludeExampleOrder = {
	orderId: string;
	total: number;
};

export type GlobalUserType = {
	name: string;
	email: string;
	createdAt: Date;
	GlobalAdminType: {
		new (): GlobalUserType_GlobalAdminType;
		(): GlobalUserType_GlobalAdminType;
	};
};

export type GlobalUserType_GlobalAdminType = ProtoFlat<GlobalUserType, {
	role: string;
	permissions: Array<unknown>;
	GlobalSuperAdminType: {
		new (): GlobalUserType_GlobalAdminType_GlobalSuperAdminType;
		(): GlobalUserType_GlobalAdminType_GlobalSuperAdminType;
	};
	GlobalAdminType: undefined;
}>;

export type GlobalUserType_GlobalAdminType_GlobalSuperAdminType = ProtoFlat<GlobalUserType_GlobalAdminType, {
	isSystemAdmin: boolean;
	accessLevel: number;
	GlobalSuperAdminType: undefined;
}>;

export type GlobalOrder = {
	orderId: string;
	total: number;
	GlobalAugmentedOrder: {
		new (): GlobalOrder_GlobalAugmentedOrder;
		(): GlobalOrder_GlobalAugmentedOrder;
	};
};

export type GlobalOrder_GlobalAugmentedOrder = ProtoFlat<GlobalOrder, {
	addition: string;
	GlobalAugmentedOrderNext: {
		new (): GlobalOrder_GlobalAugmentedOrder_GlobalAugmentedOrderNext;
		(): GlobalOrder_GlobalAugmentedOrder_GlobalAugmentedOrderNext;
	};
	GlobalAugmentedOrder: undefined;
}>;

export type GlobalOrder_GlobalAugmentedOrder_GlobalAugmentedOrderNext = ProtoFlat<GlobalOrder_GlobalAugmentedOrder, {
	next: number;
	GlobalAugmentedOrderNext: undefined;
}>;

export type RefUserType = {
	name: string;
	email: string;
	createdAt: Date;
	RefAdminType: {
		new (): RefUserType_RefAdminType;
		(): RefUserType_RefAdminType;
	};
};

export type RefUserType_RefAdminType = ProtoFlat<RefUserType, {
	role: string;
	permissions: Array<unknown>;
	RefSuperAdminType: {
		new (): RefUserType_RefAdminType_RefSuperAdminType;
		(): RefUserType_RefAdminType_RefSuperAdminType;
	};
	RefAdminType: undefined;
}>;

export type RefUserType_RefAdminType_RefSuperAdminType = ProtoFlat<RefUserType_RefAdminType, {
	isSystemAdmin: boolean;
	accessLevel: number;
	RefSuperAdminType: undefined;
}>;

export type RefOrder = {
	orderId: string;
	total: number;
	RefAugmentedOrder: {
		new (): RefOrder_RefAugmentedOrder;
		(): RefOrder_RefAugmentedOrder;
	};
};

export type RefOrder_RefAugmentedOrder = ProtoFlat<RefOrder, {
	addition: string;
	RefAugmentedOrderNext: {
		new (): RefOrder_RefAugmentedOrder_RefAugmentedOrderNext;
		(): RefOrder_RefAugmentedOrder_RefAugmentedOrderNext;
	};
	RefAugmentedOrder: undefined;
}>;

export type RefOrder_RefAugmentedOrder_RefAugmentedOrderNext = ProtoFlat<RefOrder_RefAugmentedOrder, {
	next: number;
	RefAugmentedOrderNext: undefined;
}>;

export type SomeNewType = {
	name: string;
	email: string;
	filed: number;
};

export type UserType = {
	name: string;
	email: string;
	createdAt: Date;
	AdminType: {
		new (): UserType_AdminType;
		(): UserType_AdminType;
	};
};

export type UserType_AdminType = ProtoFlat<UserType, {
	role: string;
	permissions: Array<unknown>;
	SuperAdminType: {
		new (): UserType_AdminType_SuperAdminType;
		(): UserType_AdminType_SuperAdminType;
	};
	AdminType: undefined;
}>;

export type UserType_AdminType_SuperAdminType = ProtoFlat<UserType_AdminType, {
	isSystemAdmin: boolean;
	accessLevel: number;
	SuperAdminType: undefined;
}>;

export type Order = {
	orderId: string;
	total: number;
	AugmentedOrder: {
		new (): Order_AugmentedOrder;
		(): Order_AugmentedOrder;
	};
};

export type Order_AugmentedOrder = ProtoFlat<Order, {
	addition: string;
	AugmentedOrderNext: {
		new (): Order_AugmentedOrder_AugmentedOrderNext;
		(): Order_AugmentedOrder_AugmentedOrderNext;
	};
	AugmentedOrder: undefined;
}>;

export type Order_AugmentedOrder_AugmentedOrderNext = ProtoFlat<Order_AugmentedOrder, {
	next: number;
	AugmentedOrderNext: undefined;
}>;

export type ProductType = {
	id: string;
	name: string;
	price: number;
	DigitalProductType: {
		new (): ProductType_DigitalProductType;
		(): ProductType_DigitalProductType;
	};
	PhysicalProductType: {
		new (): ProductType_PhysicalProductType;
		(): ProductType_PhysicalProductType;
	};
};

export type ProductType_DigitalProductType = ProtoFlat<ProductType, {
	downloadUrl: string;
	fileSize: number;
	format: string;
	DigitalProductType: undefined;
	PhysicalProductType: undefined;
}>;

export type ProductType_PhysicalProductType = ProtoFlat<ProductType, {
	weight: number;
	dimensions: object;
	inStock: boolean;
	PhysicalProductType: undefined;
	DigitalProductType: undefined;
}>;

export type CustomerType = {
	id: string;
	name: string;
	email: string;
	PremiumCustomerType: {
		new (): CustomerType_PremiumCustomerType;
		(): CustomerType_PremiumCustomerType;
	};
};

export type CustomerType_PremiumCustomerType = ProtoFlat<CustomerType, {
	loyaltyPoints: number;
	membershipLevel: string;
	PremiumCustomerType: undefined;
}>;

export type Invoice = {
	invoiceId: string;
	amount: number;
	issuedAt: Date;
};

export type Payment = {
	paymentId: string;
	method: string;
	status: 'pending' | 'completed' | 'failed';
};

export type ServiceType = {
	id: string;
	name: string;
	description: string;
	WebServiceType: {
		new (): ServiceType_WebServiceType;
		(): ServiceType_WebServiceType;
	};
	DatabaseServiceType: {
		new (): ServiceType_DatabaseServiceType;
		(): ServiceType_DatabaseServiceType;
	};
};

export type ServiceType_WebServiceType = ProtoFlat<ServiceType, {
	endpoint: string;
	method: string;
	WebServiceType: undefined;
	DatabaseServiceType: undefined;
}>;

export type ServiceType_DatabaseServiceType = ProtoFlat<ServiceType, {
	connectionString: string;
	poolSize: number;
	DatabaseServiceType: undefined;
	WebServiceType: undefined;
}>;

export type ConfigType = {
	env: string;
	debug: boolean;
	ProductionConfigType: {
		new (): ConfigType_ProductionConfigType;
		(): ConfigType_ProductionConfigType;
	};
};

export type ConfigType_ProductionConfigType = ProtoFlat<ConfigType, {
	env: string;
	ssl: boolean;
	caching: boolean;
	ProductionConfigType: undefined;
}>;

export type Logger = {
	level: 'debug' | 'info' | 'warn' | 'error';
	prefix: string;
};

export type Cache = {
	ttl: number;
	maxSize: number;
};

export type StrictEntity = {
	value: string;
	count: number;
	StrictChild: {
		new (): StrictEntity_StrictChild;
		(): StrictEntity_StrictChild;
	};
};

export type StrictEntity_StrictChild = ProtoFlat<StrictEntity, {
	childValue: string;
	StrictChild: undefined;
}>;

export type BaseWithPrototype = {
	baseField: number;
	name: string;
	DerivedFromBase: {
		new (): BaseWithPrototype_DerivedFromBase;
		(): BaseWithPrototype_DerivedFromBase;
	};
};

export type BaseWithPrototype_DerivedFromBase = ProtoFlat<BaseWithPrototype, {
	derivedField: number;
	extra: string;
	DerivedFromBase: undefined;
}>;

export type MyFnType = {
};

export type AssignType = {
};

export type MultiDecorated = {
	strictField: string;
};
