// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides complete TypeScript interfaces for Mnemonica types

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

// Helper type for nested type constructors
type TypeConstructor<T> = {
	new (...args: unknown[]): T;
	(...args: unknown[]): T;
};

export type StandardTypeInstance = {
	data: string;
	StandardSubtype: TypeConstructor<StandardSubtypeInstance>;
}

export type StandardSubtypeInstance = StandardTypeInstance & {
	subtypeData: string;
}

export type HiddenMethodsTypeInstance = {
	data: string;
	HiddenSubtype: TypeConstructor<HiddenSubtypeInstance>;
}

export type HiddenSubtypeInstance = HiddenMethodsTypeInstance & {
	subtypeData: string;
}

export type HiddenTypeShorthandInstance = {
	data: string;
}

export type StrictTypeInstance = {
	data: string;
}

export type BaseEntityInstance = {
	id: string;
	createdAt: Date;
	updatedAt: Date;
	UserEntity: TypeConstructor<UserEntityInstance>;
	ProductEntity: TypeConstructor<ProductEntityInstance>;
}

export type UserEntityInstance = BaseEntityInstance & {
	username: string;
	email: string;
	isActive: boolean;
	AdminEntity: TypeConstructor<AdminEntityInstance>;
}

export type AdminEntityInstance = UserEntityInstance & {
	role: string;
	permissions: Array<string>;
}

export type ProductEntityInstance = BaseEntityInstance & {
	sku: string;
	name: string;
	price: number;
}

export type ConfigurableEntityInstance = {
	config: object;
}

export type ExcludeExampleUserInstance = {
	name: string;
	email: string;
}

export type ExcludeExampleOrderInstance = {
	orderId: string;
	total: number;
}

export type GlobalUserTypeInstance = {
	name: string;
	email: string;
	createdAt: Date;
	GlobalAdminType: TypeConstructor<GlobalAdminTypeInstance>;
}

export type GlobalAdminTypeInstance = GlobalUserTypeInstance & {
	role: string;
	permissions: Array<unknown>;
	GlobalSuperAdminType: TypeConstructor<GlobalSuperAdminTypeInstance>;
}

export type GlobalSuperAdminTypeInstance = GlobalAdminTypeInstance & {
	isSystemAdmin: boolean;
	accessLevel: number;
}

export type GlobalOrderInstance = {
	orderId: string;
	total: number;
	GlobalAugmentedOrder: TypeConstructor<GlobalAugmentedOrderInstance>;
}

export type GlobalAugmentedOrderInstance = GlobalOrderInstance & {
	addition: string;
	GlobalAugmentedOrderNext: TypeConstructor<GlobalAugmentedOrderNextInstance>;
}

export type GlobalAugmentedOrderNextInstance = GlobalAugmentedOrderInstance & {
	next: number;
}

export type UserTypeInstance = {
	name: string;
	email: string;
	createdAt: Date;
	AdminType: TypeConstructor<AdminTypeInstance>;
}

export type AdminTypeInstance = UserTypeInstance & {
	role: string;
	permissions: Array<unknown>;
	SuperAdminType: TypeConstructor<SuperAdminTypeInstance>;
}

export type SuperAdminTypeInstance = AdminTypeInstance & {
	isSystemAdmin: boolean;
	accessLevel: number;
}

export type OrderInstance = {
	orderId: string;
	total: number;
	AugmentedOrder: TypeConstructor<AugmentedOrderInstance>;
}

export type AugmentedOrderInstance = OrderInstance & {
	addition: string;
	AugmentedOrderNext: TypeConstructor<AugmentedOrderNextInstance>;
}

export type AugmentedOrderNextInstance = AugmentedOrderInstance & {
	next: number;
}

export type RefUserTypeInstance = {
	name: string;
	email: string;
	createdAt: Date;
	RefAdminType: TypeConstructor<RefAdminTypeInstance>;
}

export type RefAdminTypeInstance = RefUserTypeInstance & {
	role: string;
	permissions: Array<unknown>;
	RefSuperAdminType: TypeConstructor<RefSuperAdminTypeInstance>;
}

export type RefSuperAdminTypeInstance = RefAdminTypeInstance & {
	isSystemAdmin: boolean;
	accessLevel: number;
}

export type RefOrderInstance = {
	orderId: string;
	total: number;
	RefAugmentedOrder: TypeConstructor<RefAugmentedOrderInstance>;
}

export type RefAugmentedOrderInstance = RefOrderInstance & {
	addition: string;
	RefAugmentedOrderNext: TypeConstructor<RefAugmentedOrderNextInstance>;
}

export type RefAugmentedOrderNextInstance = RefAugmentedOrderInstance & {
	next: number;
}

export type ProductTypeInstance = {
	id: string;
	name: string;
	price: number;
	DigitalProductType: TypeConstructor<DigitalProductTypeInstance>;
	PhysicalProductType: TypeConstructor<PhysicalProductTypeInstance>;
}

export type DigitalProductTypeInstance = ProductTypeInstance & {
	downloadUrl: string;
	fileSize: number;
	format: string;
}

export type PhysicalProductTypeInstance = ProductTypeInstance & {
	weight: number;
	dimensions: object;
	inStock: boolean;
}

export type CustomerTypeInstance = {
	id: string;
	name: string;
	email: string;
	PremiumCustomerType: TypeConstructor<PremiumCustomerTypeInstance>;
}

export type PremiumCustomerTypeInstance = CustomerTypeInstance & {
	loyaltyPoints: number;
	membershipLevel: string;
}

export type InvoiceInstance = {
	invoiceId: string;
	amount: number;
	issuedAt: Date;
}

export type PaymentInstance = {
	paymentId: string;
	method: string;
	status: string;
}

export type ServiceTypeInstance = {
	id: string;
	name: string;
	description: string;
	WebServiceType: TypeConstructor<WebServiceTypeInstance>;
	DatabaseServiceType: TypeConstructor<DatabaseServiceTypeInstance>;
}

export type WebServiceTypeInstance = ServiceTypeInstance & {
	endpoint: string;
	method: string;
}

export type DatabaseServiceTypeInstance = ServiceTypeInstance & {
	connectionString: string;
	poolSize: number;
}

export type ConfigTypeInstance = {
	env: string;
	debug: boolean;
	ProductionConfigType: TypeConstructor<ProductionConfigTypeInstance>;
}

export type ProductionConfigTypeInstance = ConfigTypeInstance & {
	env: string;
	ssl: boolean;
	caching: boolean;
}

export type LoggerInstance = {
	level: string;
	prefix: string;
}

export type CacheInstance = {
	ttl: number;
	maxSize: number;
}

export type StrictEntityInstance = {
	value: string;
	count: number;
	StrictChild: TypeConstructor<StrictChildInstance>;
}

export type StrictChildInstance = StrictEntityInstance & {
	childValue: string;
}

export type BaseWithPrototypeInstance = {
	baseField: number;
	name: string;
	DerivedFromBase: TypeConstructor<DerivedFromBaseInstance>;
}

export type DerivedFromBaseInstance = BaseWithPrototypeInstance & {
	derivedField: number;
	extra: string;
}

export type MyFnTypeInstance = {
}

export type AssignTypeInstance = {
}

export type MultiDecoratedInstance = {
	strictField: string;
}
